### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ssnjrthegr8** [mzrimsek/track-my-playtime#76]
Hi, can I contribute by designing a logo for this project?

**Comment by mzrimsek** [comment]
I would love to see what you come up with!

**Comment by ssnjrthegr8** [comment]
![flowroot1064](https://user-images.githubusercontent.com/38104354/40623012-42e21a02-62c2-11e8-95df-7b771abfb197.png)

How does this look? The idea is a mix of a stopwatch and a gamepad. Stopwatch as in tracking time and gamepad to indicate that its tracking how long you are playing a game

**Comment by mzrimsek** [comment]
Oh wow that's really good. I love it. Would it be possible to get a couple different versions? I would love to use just the logo part as a favicon.

I'll also credit you in the readme once I add the icon into the project.

**Comment by mzrimsek** [comment]
This is perfect!

I will definitely be adding a shout out to in the README once I add this to the project!

**Comment by mzrimsek** [comment]
I think if I could get just a vector version of just the logo that could be great for use on the website.

I was looking at this for generating icons because I'm not quite sure of all the images I would need: https://realfavicongenerator.net/

I do intend of making native apps for the website in the future.

Man I really do love this icon though. I had had similar ideas for combining a gamepad and a stopwatch but this outdoes any idea I had.

**Comment by ssnjrthegr8** [comment]
- Here is the PR I made for the vector source file: https://github.com/mzrimsek/track-my-playtime/pull/85
- If you want more files, go to: https://drive.google.com/drive/folders/1eY7Phs-kMdujCFLiIEFY72GKdJ4YoEQk?usp=sharing 
- Font Used: https://fonts.google.com/specimen/Titillium+Web

#### If you need anything else just tell me and I will do it. Maybe you need an app logo right? If you want an app logo just tell me and I will do it. Also I will need to for what all platforms I have to make the app icon for. Thank you for this opportunity!
